### ISSUE TITLE
Module 4.14 payload

### ISSUE THREAD

**Issue by neogeek13** [mulespaceprogram/mulespaceprogram.github.io#1]
Module 4.14 payload as included in the Module 4 payload.txt file will not work for the first portion of the 4.14 module exercise. It's configured to work only for the second flow scenario. 

For the first flow, it needs to be modified to match what is used in the video before the Postman call will work.

This needs to be removed:
```var planets = [```

This needs to be added in its stead:
```---[```

The last 2 lines of the file need to be removed.

Perhaps having either 2 sections for the different versions of the same file OR having two differently named files in the Module 4 folder would work?

**Comment by amritsinghbains** [comment]
You are right, can you create a new file tagging with appropriate video number, and submit a pull request?

**Comment by neogeek13** [comment]
Can you grant me access to your repo? I'm ready to push a branch for your review.

When I attempt to push (either to a new branch or master), I get:
```
ERROR: Permission to mulespaceprogram/mulespaceprogram.github.io.git denied to neogeek13.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by amritsinghbains** [comment]
try now

**Comment by amritsinghbains** [comment]
Fixed with https://github.com/mulespaceprogram/mulespaceprogram.github.io/pull/2
